version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3308:3306
        networks:
            mynetwork:
                aliases:
                    - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8083:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            mynetwork:

    adminer:
        image: adminer
        ports:
            - 8084:8080
        networks:
            mynetwork:

networks:
    mynetwork:
        driver: bridge
